source 'https://github.com/NJHu/NJSpecs.git' # NJ 私有源
source 'https://github.com/CocoaPods/Specs.git' # 公有源


platform :ios, '10.3'

use_frameworks!

target 'NJSisPlayPage_Example' do
  pod 'NJSisPlayPage', :path => '../'

  target 'NJSisPlayPage_Tests' do
    inherit! :search_paths

    
  end
end
